[project]
name = "home-work-5"
version = "0.1.0"
description = "ДЗ 5"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "pytest>=8.4.2",
]


[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1"
]
