services:
  todo-app:
    build: ./todo_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_FILE=/app/data/todo.db
    restart: always

  shorturl-app:
    build: ./shorturl_app
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    environment:
      - DB_FILE=/app/data/shorturl.db
    restart: always
