[project]
name = "home-work-1"
version = "0.1.0"
description = "ДЗ 1"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1"
]
